### ISSUE TITLE
Nimbus causes a purple color filter to apply to the screen until the planet is left.

### ISSUE THREAD

**Issue by GuapoChee** [Toliann/Nimbus#1]
Nimbus was downloaded from the Tolian Moon Pack, and upon landing there, a dark purple color filter of some sort gets applied to the player's screen. This applies to the Planet's surface and the interior as well. It goes away upon leaving the planet. It happened even when the only mods in use were Tolian's Moon Pack, the GeneralImprovements Mod, and their respective dependencies. 
![20240501190715_1](https://github.com/Toliann/Nimbus/assets/111323990/5781d1eb-3bb2-45df-ac1f-b346cdbfba3e)

**Comment by Toliann** [comment]
Check the latest version
